# Generated by Django 3.0.8 on 2020-07-15 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barberia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('latitud', models.CharField(max_length=200)),
                ('longitud', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('horario', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barberia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Barberia')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Cliente')),
                ('hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Hora')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to='cortes')),
                ('precio', models.CharField(max_length=200)),
                ('barberia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Barberia')),
            ],
        ),
        migrations.CreateModel(
            name='Barbero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('avatar', models.ImageField(upload_to='avatars')),
                ('barberia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Barberia')),
            ],
        ),
    ]
